// <auto-generated />
using DevizWebApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DevizWebApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260108045033_RenderInit")]
    partial class RenderInit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DevizWebApp.Models.Deviz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("CUI")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Constatare")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Firma")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("KM")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LucrariConvenite")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Masina")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("NrDeviz")
                        .HasColumnType("integer");

                    b.Property<string>("NrInmat")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PieseAduseClient")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SerieCaroserie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SerieMotor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("NrDeviz")
                        .IsUnique();

                    b.ToTable("Devize");
                });

            modelBuilder.Entity("DevizWebApp.Models.DevizItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantitate")
                        .HasColumnType("numeric");

                    b.Property<string>("Denumire")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("DevizId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PretUnitar")
                        .HasColumnType("numeric");

                    b.Property<string>("Tip")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("TotalLinie")
                        .HasColumnType("numeric");

                    b.Property<string>("UM")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("DevizId");

                    b.ToTable("DevizItems");
                });

            modelBuilder.Entity("DevizWebApp.Models.Factura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientAdresa")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("ClientCUI")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ClientNume")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("NrFactura")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalGeneral")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalManopera")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalPiese")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("NrFactura")
                        .IsUnique();

                    b.ToTable("Facturi");
                });

            modelBuilder.Entity("DevizWebApp.Models.FacturaDeviz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DevizId")
                        .HasColumnType("integer");

                    b.Property<int>("FacturaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DevizId");

                    b.HasIndex("FacturaId");

                    b.ToTable("FacturaDevize");
                });

            modelBuilder.Entity("DevizWebApp.Models.FacturaItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantitate")
                        .HasColumnType("numeric");

                    b.Property<string>("Denumire")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("FacturaId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PretUnitar")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalLinie")
                        .HasColumnType("numeric");

                    b.Property<string>("UM")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("FacturaId");

                    b.ToTable("FacturaItems");
                });

            modelBuilder.Entity("DevizWebApp.Models.DevizItem", b =>
                {
                    b.HasOne("DevizWebApp.Models.Deviz", "Deviz")
                        .WithMany("Items")
                        .HasForeignKey("DevizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deviz");
                });

            modelBuilder.Entity("DevizWebApp.Models.FacturaDeviz", b =>
                {
                    b.HasOne("DevizWebApp.Models.Deviz", "Deviz")
                        .WithMany()
                        .HasForeignKey("DevizId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DevizWebApp.Models.Factura", "Factura")
                        .WithMany("FacturaDevize")
                        .HasForeignKey("FacturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deviz");

                    b.Navigation("Factura");
                });

            modelBuilder.Entity("DevizWebApp.Models.FacturaItem", b =>
                {
                    b.HasOne("DevizWebApp.Models.Factura", "Factura")
                        .WithMany("Items")
                        .HasForeignKey("FacturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Factura");
                });

            modelBuilder.Entity("DevizWebApp.Models.Deviz", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("DevizWebApp.Models.Factura", b =>
                {
                    b.Navigation("FacturaDevize");

                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
